### ISSUE TITLE
Some incompatibility scalacOptions with 2.11.*

### ISSUE THREAD

**Issue by wi101** [scalaz/scalaz-sbt#21]
In order to unify dependencies in scalaz projects, we added `scalaz-sbt` plugin
It works with scala 2.12.* 
when we had 2.11.* Scala version, we got this error:
```
[error] 'constant' is not a valid choice for '-Xlint'
[error] bad option: '-Ywarn-extra-implicit'
[error] (Compile / compileIncremental) Compilation failed
```
